version: "3.5"
services:
  cemp-bms:
    container_name: stock-fetch-data
    image: stock-fetch-data:latest
    restart: always
    build:
      context: ./stock-fetch-data
      dockerfile: dockerfile
    ports:
      - "33001:33001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  stock-gateway:
    container_name: stock-gateway
    image: stock-gateway:latest
    restart: always
    build:
      context: ./stock-gateway
      dockerfile: dockerfile
    ports:
      - "33100:33100"
    volumes:
      - type: bind
        source: /app/docker/elk/filebeat/logs
        target: /app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=dev
