version: "3.5"
services:
  stock-fetch-data:
    container_name: stock-fetch-data
    network_mode: host
    image: stock-fetch-data:latest
    restart: always
    build:
      context: ./stock-fetch-data
      dockerfile: dockerfile
    ports:
      - "33001:33001"
    volumes:
      - type: bind
        source: /app/docker/elk/filebeat/logs
        target: /app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  stock-core:
    container_name: stock-core
    network_mode: host
    image: stock-core:latest
    restart: always
    build:
      context: ./stock-core
      dockerfile: dockerfile
    ports:
      - "33002:33002"
    volumes:
      - type: bind
        source: /app/docker/elk/filebeat/logs
        target: /app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  stock-gateway:
    container_name: stock-gateway
    network_mode: host
    image: stock-gateway:latest
    restart: always
    build:
      context: ./stock-gateway
      dockerfile: dockerfile
    ports:
      - "33100:33100"
      - "8719:8719"
    volumes:
      - type: bind
        source: /app/docker/elk/filebeat/logs
        target: /app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  stock-current-kpi:
    container_name: stock-current-kpi
    network_mode: host
    image: stock-current-kpi:latest
    restart: always
    build:
      context: ./stock-current-kpi
      dockerfile: dockerfile
    ports:
      - "33004:33004"
    volumes:
      - type: bind
        source: /app/docker/elk/filebeat/logs
        target: /app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
