version: "3.5"
services:
  cemp-bms:
    container_name: cemp-bms
    image: cemp-bms-dev:latest
    restart: always
    build:
      context: ./cemp-bms
      dockerfile: dockerfile
    ports:
      - "30001:30001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

