version: "3.5"
services:
  cemp-bms:
    container_name: stock-fetch-data
    image: stock-fetch-data:latest
    restart: always
    build:
      context: ./stock-fetch-data
      dockerfile: dockerfile
    ports:
      - "33001:33001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

