spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 39.98.82.109:8848
      discovery:
        namespace: e3bca0e8-505d-42d4-a2e7-686fb8ff2659
        group: DEFAULT_GROUP
      config:
        server-addr: 39.98.82.109:8848
        namespace: e3bca0e8-505d-42d4-a2e7-686fb8ff2659
        group: DEFAULT_GROUP
        file-extension: yaml
  config:
    import:
      - optional:nacos:${spring.application.name}
