spring:
  application:
    name: stock-fetch-data
  profiles:
    active: dev
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Dubbo 或者 Feign 等会存在重复定义的服务
  data:
    redis:
      host: 39.98.82.109
      port: 6379
      database: 0
      password: landleaf123
nacos:
  logging:
    default:
      config:
        enabled: false

server:
  port: 33001
  servlet:
    context-path: /
